### ISSUE TITLE
作者什么时候支持一下webstrom？

### ISSUE THREAD

**Issue by jackzhujie** [hyb1996/Auto.js-VSCode-Extension#12]
本人webstrom死粉了，不想用vs code

**Comment by zwmmm** [comment]
几乎不可能，vscode的插件都是用js写的 ws的插件好像得用Kotlin开发吧，会这个语言的我还没见过

**Comment by jackzhujie** [comment]
> 几乎不可能，vscode的插件都是用js写的 ws的插件好像得用Kotlin开发吧，会这个语言的我还没见过

原来是这样

**Comment by hyb1996** [comment]
当然不是语言的问题。Kotlin现在用得非常多，Auto.js开源代码中也包含了不少Kotlin。问题在于WebStrom是付费应用，不适合作为一般用户的推荐开发工具。短时间内不会支持。
