### ISSUE TITLE
wsl里面wifi链接失败

### ISSUE THREAD

**Issue by cool-delete** [hyb1996/Auto.js-VSCode-Extension#16]
@710850609 你尝试过在wsl里面wifi链接吗
![image](https://user-images.githubusercontent.com/13638610/92982451-cc871080-f4d0-11ea-93dc-ebbb2196e4fd.png)
开启服务后
auto提示链接失败

**Comment by 710850609** [comment]
没有，为什么要在wsl里面开vscode

**Comment by 710850609** [comment]
wsl2的ip和win10ip是不一样的

**Comment by cool-delete** [comment]
@710850609 ...没办法啊 安装vscode扩展要求装在wsl...选不了 我记得以前是可以链接的 就算ip不一样

**Comment by cool-delete** [comment]
大概是1个月之前

**Comment by cool-delete** [comment]
@710850609 
如果关闭wsl环境后 使用本地系统开启vscode
则绑定0.0.0.0
https://user-images.githubusercontent.com/13638610/93023151-8d1b0a00-f61f-11ea-87dd-e66a481d5b02.png
就能成功 
能否改为不要安装在wsl 主要工具都在wsl里面 关闭wsl很多插件都使用不了..
