### ISSUE TITLE
Unexpected token { in JSON at position 51 	at JSON.parse (<anonymous>) 

### ISSUE THREAD

**Issue by shiny** [hyb1996/Auto.js-VSCode-Extension#2]
![image](https://user-images.githubusercontent.com/117487/45157882-ed973580-b214-11e8-810b-8d42b91fcdab.png)

console.log 时候，有时候会遇到这个报错

**Comment by hyb1996** [comment]
已修复，使用Auto.js 4.0.3和最新版插件即可
