### ISSUE TITLE
连接电脑, 无法连接成功

### ISSUE THREAD

**Issue by xgqfrms** [hyb1996/Auto.js-VSCode-Extension#22]
# 连接电脑, 无法连接成功

> 端口：vscode 运行 `Auto.js:Start Server` 后没有提供任何端口信息，看了下源码端口是 `9317`,

## 环境

> wifi

http://192.168.0.1

> Mac

http://192.168.0.100

> Android

http://192.168.0.105

> 连接电脑

http://192.168.0.100:9317/

![image](https://user-images.githubusercontent.com/7291672/162620532-3f4cd789-e4bc-42eb-9930-c0f7f9827a92.png)

**Comment by heibai6** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
