### ISSUE TITLE
[功能需求] 把设备的屏幕截图取回来....

### ISSUE THREAD

**Issue by fcying** [hyb1996/Auto.js-VSCode-Extension#7]
方便在电脑上取色操作....这样可以不用去找第三方的远程取色了.

**Comment by hyb1996** [comment]
Auto.js Pro会支持这个功能
有关pro的信息，参见 https://pro.autojs.org

**Comment by fcying** [comment]
已经买过了. 原来这功能已经在计划里了. 期待
